name: Static Analysis

on:
  push:
    paths:
      - 'terraform/environments/**'
      - 'terraform/infra/**'
      - '.github/workflows/infra-statics-tests.yml'

jobs:
  terraform-static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.44.1

      - name: Setup tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: .

      - name: Terraform Format Check
        run: |
          terraform fmt -check -recursive
        working-directory: .

      - name: Terraform Validate
        run:  |
          # Loop through each subdirectory in terraform/environments/
          for dir in terraform/environments/*/; do
            # Check if main.tf exists in the directory
            if [ -f "$dir/main.tf" ]; then
              echo "--- Validating $(basename "$dir") ---"
            
              # Change into the directory
              pushd "$dir" > /dev/null
            
              # Run terraform init without a backend
              terraform init -backend=false
            
              # Run terraform validate
              terraform validate
            
              # Change back to the original directory
              popd > /dev/null
            
              echo "--- $(basename "$dir") Validation Complete ---"
            else
              echo "Skipping $dir - no main.tf found."
            fi
          done

      - name: TFLint
        run: |
          tflint --init
          tflint --recursive

       # Perform a security scan of the terraform code tfsec
      - name: tfsec
        uses: tfsec/tfsec-sarif-action@master
        with:
          sarif_file: tfsec.sarif         

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: tfsec.sarif